name: Build audit image

on:
  push:
    branches:
      - main
    paths:
      - 'tools/audit/**'
      - '.github/workflows/build-audit-image.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'tools/audit/**'
      - '.github/workflows/build-audit-image.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: tools/audit
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/alexandreroman/resumebot-audit:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trigger-gitops:
    needs:
    - build-and-push
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      TARGET_OWNER: alexandreroman
      TARGET_REPO: rpilab
      TARGET_WORKFLOW: gitops.yaml
    steps:
    - name: trigger-gitops
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$TARGET_OWNER/$TARGET_REPO/actions/workflows/$TARGET_WORKFLOW/dispatches \
          -d '{"ref":"main"}'
